In [2]:
# Import the packages

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [3]:
# Import dataset

police=pd.read_csv(r"C:\Users\HP Victus\Desktop\AnalytixLabs\GitHub\Data\raw_data\police.csv")

In [4]:
police.head(3)

,stop_date,stop_time,county_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,02-01-2005,01:55,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,18-01-2005,08:15,NaN,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,23-01-2005,23:15,NaN,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [5]:
# Shape

police.shape

(91741, 15)

In [6]:
# Dimensions

police.ndim

2

In [7]:
# Duplicate rows

police.duplicated().sum()

np.int64(479)

In [8]:
# Remove duplicates

police.drop_duplicates(keep='first',inplace=True)

In [9]:
police.duplicated().sum()

np.int64(0)

In [10]:
police.info()

<class 'pandas.DataFrame'>
Index: 91262 entries, 0 to 91740
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   stop_date           91262 non-null  str
 1   stop_time           91262 non-null  str
 2   county_name         0 non-null      float64
 3   driver_gender       86137 non-null  str
 4   driver_age_raw      86145 non-null  float64
 5   driver_age          85852 non-null  float64
 6   driver_race         86139 non-null  str
 7   violation_raw       86139 non-null  str
 8   violation           86139 non-null  str
 9   search_conducted    91262 non-null  bool
 10  search_type         3187 non-null   str
 11  stop_outcome        86139 non-null  str
 12  is_arrested         86139 non-null  object
 13  stop_duration       86139 non-null  str
 14  drugs_related_stop  91262 non-null  bool
dtypes: bool(2), float64(3), object(1), str(9)
memory usage: 15.3+ MB

In [11]:
# Datatypes

police.dtypes

stop_date                 str
stop_time                 str
county_name           float64
driver_gender             str
driver_age_raw        float64
driver_age            float64
driver_race               str
violation_raw             str
violation                 str
search_conducted         bool
search_type               str
stop_outcome              str
is_arrested            object
stop_duration             str
drugs_related_stop       bool
dtype: object

In [12]:
# Missing values

police.isna().sum()

stop_date                 0
stop_time                 0
county_name           91262
driver_gender          5125
driver_age_raw         5117
driver_age             5410
driver_race            5123
violation_raw          5123
violation              5123
search_conducted          0
search_type           88075
stop_outcome           5123
is_arrested            5123
stop_duration          5123
drugs_related_stop        0
dtype: int64

In [13]:
# Missing value percentage

police.isna().sum()/police.shape[0]*100

stop_date               0.000000
stop_time               0.000000
county_name           100.000000
driver_gender           5.615700
driver_age_raw          5.606934
driver_age              5.927988
driver_race             5.613508
violation_raw           5.613508
violation               5.613508
search_conducted        0.000000
search_type            96.507857
stop_outcome            5.613508
is_arrested             5.613508
stop_duration           5.613508
drugs_related_stop      0.000000
dtype: float64

In [14]:
# Drop unnecessary columns

police.drop(columns='county_name',inplace=True)

In [15]:
police.columns

Index(['stop_date', 'stop_time', 'driver_gender', 'driver_age_raw',
       'driver_age', 'driver_race', 'violation_raw', 'violation',
       'search_conducted', 'search_type', 'stop_outcome', 'is_arrested',
       'stop_duration', 'drugs_related_stop'],
      dtype='str')

In [16]:
police.isna().sum()/police.shape[0]*100

stop_date              0.000000
stop_time              0.000000
driver_gender          5.615700
driver_age_raw         5.606934
driver_age             5.927988
driver_race            5.613508
violation_raw          5.613508
violation              5.613508
search_conducted       0.000000
search_type           96.507857
stop_outcome           5.613508
is_arrested            5.613508
stop_duration          5.613508
drugs_related_stop     0.000000
dtype: float64

In [17]:
police.search_type=police.search_type.fillna('No search')

In [18]:
police.isna().sum()/police.shape[0]*100

stop_date             0.000000
stop_time             0.000000
driver_gender         5.615700
driver_age_raw        5.606934
driver_age            5.927988
driver_race           5.613508
violation_raw         5.613508
violation             5.613508
search_conducted      0.000000
search_type           0.000000
stop_outcome          5.613508
is_arrested           5.613508
stop_duration         5.613508
drugs_related_stop    0.000000
dtype: float64

In [19]:
# Change dtypes

police['stop_date']=pd.to_datetime(police['stop_date'],format='%d-%m-%Y')
police['stop_time']=pd.to_datetime(police['stop_time'],format='%H:%M')

In [20]:
# Data audit for numerical data

def continuous_variable_summary(x):
    #freq and missing values
    n_total=x.shape[0]
    n_miss=x.isna().sum()
    perc_miss=n_miss/n_total*100

    #Outliers
    q1=x.quantile(0.25)
    q3=x.quantile(0.75)
    iqr=q3-q1
    lc_iqr=q1-1.5*iqr
    uc_iqr=q3+1.5*iqr
    return pd.Series([x.dtype,x.nunique(),n_total,n_miss,perc_miss,x.sum(),x.mean(),x.std(),x.var(),lc_iqr,uc_iqr,x.min(),
                      x.quantile(0.01),x.quantile(0.05),x.quantile(0.10),x.quantile(0.25),x.median(),
                      x.quantile(0.75),x.quantile(0.90),x.quantile(0.95),x.quantile(0.99),x.max()],index=
                     ['dtype','cardinality','n_tot','miss','perc_miss','sum','mean','std','var','lc_iqr','uc_iqr'
                      ,'min','p1','p5','p10','p25','p50','p75','p90','p95','p99','max'])

In [21]:
police.select_dtypes(['float64','int64']).apply(continuous_variable_summary)

            driver_age_raw  driver_age
dtype              float64     float64
cardinality             97          78
n_tot                91262       91262
miss                  5117        5410
perc_miss         5.606934    5.927988
sum            169748499.0   2920063.0
mean           1970.497406   34.012755
std             110.882213   12.737448
var           12294.865245  162.242572
lc_iqr              1937.0        -7.0
uc_iqr              2017.0        73.0
min                    0.0        15.0
p1                  1940.0        18.0
p5                  1951.0        19.0
p10                 1957.0        20.0
p25                 1967.0        23.0
p50                 1980.0        31.0
p75                 1987.0        43.0
p90                 1991.0        53.0
p95                 1993.0        58.0
p99                 1995.0        68.0
max                 8801.0        99.0

In [22]:
# Data audit for categorical data

# EDA categorical data
def categorical_var_summary(x):
    Mode = x.value_counts().sort_values(ascending = False)[0:1].reset_index()
    return pd.Series([x.count(), x.isnull().sum(), Mode.iloc[0, 0], Mode.iloc[0, 1], 
                          round(Mode.iloc[0, 1] * 100/x.count(), 2),x.nunique()], 
                  index = ['N', 'NMISS', 'MODE', 'FREQ', 'PERCENT','CARDINALITY'])

In [23]:
police.select_dtypes(['str','object']).apply(categorical_var_summary)

,driver_gender,driver_race,violation_raw,violation,search_type,stop_outcome,is_arrested,stop_duration
N,86137,86139,86139,86139,91262,86139,86139,86139
NMISS,5125,5123,5123,5123,0,5123,5123,5123
MODE,M,White,Speeding,Speeding,No search,Citation,False,0-15 Min
FREQ,62691,61968,48320,48320,88075,76777,83244,69369
PERCENT,72.78,71.94,56.1,56.1,96.51,89.13,96.64,80.53
CARDINALITY,2,5,12,6,25,6,2,5

In [24]:
# Outlier treatment

# Outlier treatment on numerical column

def outlier(x):
    q1=x.quantile(0.25)
    q3=x.quantile(0.75)
    iqr=q3-q1
    lc_iqr=q1-1.5*iqr
    uc_iqr=q3+1.5*iqr
    return x.clip(lower=lc_iqr,upper=uc_iqr)

In [25]:
num_cols=police.select_dtypes(['int64','float64']).columns
police[num_cols]=police[num_cols].apply(outlier)

In [26]:
# Missing value imputation

def missing_imputation(x):
    if (x.dtype=='float64') | (x.dtype=='int64'):
        x=x.fillna(x.mean())
    elif (x.dtype=='str') | (x.dtype=='object'):
        x=x.fillna(x.mode()[0])
    return(x)

In [27]:
police=police.apply(missing_imputation)

In [28]:
police.isna().sum()

stop_date             0
stop_time             0
driver_gender         0
driver_age_raw        0
driver_age            0
driver_race           0
violation_raw         0
violation             0
search_conducted      0
search_type           0
stop_outcome          0
is_arrested           0
stop_duration         0
drugs_related_stop    0
dtype: int64

In [29]:
# Change true fales to 0 and 1

police=police.replace({True:1,False:0})

In [30]:
# data conversion of remaining columns

police['driver_age_raw']=police['driver_age_raw'].astype(int)
police['driver_age']=police['driver_age'].astype(int)

In [31]:
police.head(3)

,stop_date,stop_time,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,2005-01-02,1900-01-01 01:55:00,M,1985,20,White,Speeding,Speeding,0,No search,Citation,0,0-15 Min,0
1,2005-01-18,1900-01-01 08:15:00,M,1965,40,White,Speeding,Speeding,0,No search,Citation,0,0-15 Min,0
2,2005-01-23,1900-01-01 23:15:00,M,1972,33,White,Speeding,Speeding,0,No search,Citation,0,0-15 Min,0

In [32]:
police.stop_duration=police.stop_duration.replace({'2':'0-15 Min','1':'0-15 Min'})

In [33]:
police.stop_duration.value_counts()

stop_duration
0-15 Min     74494
16-30 Min    13566
30+ Min       3202
Name: count, dtype: int64

In [34]:
police.search_type.value_counts()

search_type
No search                                                   88075
Incident to Arrest                                           1214
Probable Cause                                                890
Inventory                                                     220
Reasonable Suspicion                                          197
Protective Frisk                                              160
Incident to Arrest,Inventory                                  129
Incident to Arrest,Probable Cause                             105
Probable Cause,Reasonable Suspicion                            75
Incident to Arrest,Inventory,Probable Cause                    34
Probable Cause,Protective Frisk                                33
Incident to Arrest,Protective Frisk                            32
Inventory,Probable Cause                                       22
Incident to Arrest,Reasonable Suspicion                        13
Inventory,Protective Frisk                                     11
Incident to Arrest,Inventory,Protective Frisk                  11
Protective Frisk,Reasonable Suspicion                          11
Incident to Arrest,Probable Cause,Protective Frisk             10
Incident to Arrest,Probable Cause,Reasonable Suspicion          6
Incident to Arrest,Inventory,Reasonable Suspicion               4
Inventory,Reasonable Suspicion                                  4
Inventory,Probable Cause,Protective Frisk                       2
Inventory,Probable Cause,Reasonable Suspicion                   2
Incident to Arrest,Protective Frisk,Reasonable Suspicion        1
Probable Cause,Protective Frisk,Reasonable Suspicion            1
Name: count, dtype: int64

In [35]:
# Make multiple reasons as 'Multiple reasons'

police['search_type']=police['search_type'].apply(lambda x: 'Multiple Types' if ',' in str(x) else x)

In [36]:
police.search_type.value_counts()

search_type
No search               88075
Incident to Arrest       1214
Probable Cause            890
Multiple Types            506
Inventory                 220
Reasonable Suspicion      197
Protective Frisk          160
Name: count, dtype: int64

In [37]:
police=police.rename(columns=({'driver_age_raw':'year_of_birth'}))

In [38]:
# Feature engineering

In [39]:
police['year']=police['stop_date'].dt.year
police['month']=police['stop_date'].dt.month_name()
police['day_of_week']=police['stop_date'].dt.day_name()
police['hour']=police.stop_time.dt.hour

In [40]:
police['Time_bin']=np.where((police.hour>=0)&(police.hour<=6),'Night',np.where((police.hour>=7)&(police.hour<=12),'Morning',np.where((police.hour>=13)&(police.hour<=18),'Afternoon','Evening')))

In [41]:
police.stop_time=police.stop_time.dt.time

In [42]:
police['age_group']=np.where(police.driver_age<=20,'<=20',np.where((police.driver_age>=21)&(police.driver_age<=40),'21-40',np.where((police.driver_age>=41)&(police.driver_age<=60),'41-60','61-80')))

In [ ]:
police.head(3)

,stop_date,stop_time,driver_gender,year_of_birth,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,year,month,day_of_week,hour,Time_bin,age_group
0,2005-01-02,01:55:00,M,1985,20,White,Speeding,Speeding,0,No search,Citation,0,0-15 Min,0,2005,January,Sunday,1,Night,<=20
1,2005-01-18,08:15:00,M,1965,40,White,Speeding,Speeding,0,No search,Citation,0,0-15 Min,0,2005,January,Tuesday,8,Morning,21-40
2,2005-01-23,23:15:00,M,1972,33,White,Speeding,Speeding,0,No search,Citation,0,0-15 Min,0,2005,January,Sunday,23,Evening,21-40